FROM golang:alpine
RUN mkdir /app
ADD Dockerfile.run hello.go /app/
WORKDIR /app
RUN env GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o hello-go-web .
# Output a tarball which can be piped into `docker build -f Dockerfile.run -`
CMD tar -cf - -C /app Dockerfile.run -C /app hello-go-web
